### PR TITLE
Depth First Search added to PathFinding Algorithm

### PR DESCRIPTION
**Pull request by charlie219**
PathFinding Algorithms added to the MainMenu and DFS added

### CODE REVIEW

**Comment by charlie219** [comment]
Screen Flickering Issue resolved in Rat_in_the _Maze.py and Knights_Tour.py

**Comment by karan236** [comment]
I have gone through this pull request. There are certain bugs that needs to be fixed before merging this pull request. I ll let you know the details of it over a telephone conversation.

Major improvement seen in terms of readability of Code. Good Job.

**Comment by charlie219** [comment]
All the desired changes proposed by @karan236  are made.

**Comment by karan236** [comment]
Everything seemed fine to me. All the raised issues are fixed.
You can merge it with master.

**Pull request merged**
